name: Build and Deploy

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  build_deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Create development env file 🗃️
        run: |
          touch gatsby.development.env
          echo GATSBY_ENVIRONMENT =${{ secrets.GATSBY_ENVIRONMENT }} >> gatsby.development.env
          echo GATSBY_LD_CLIENT_ID =${{ secrets.GATSBY_LD_CLIENT_ID }} >> gatsby.development.env
          echo GATSBY_LD_API_KEY =${{ secrets.GATSBY_LD_API_KEY }} >> gatsby.development.env
          echo GATSBY_CONTENTFUL_API_KEY =${{ secrets.GATSBY_CONTENTFUL_API_KEY }} >> gatsby.development.env
          echo GATSBY_CONTENTFUL_DOWNLOAD_LOCAL =${{ secrets.GATSBY_CONTENTFUL_DOWNLOAD_LOCAL }} >> gatsby.development.env
          echo GATSBY_CONTENTFUL_ENVIRONMENT =${{ secrets.GATSBY_CONTENTFUL_ENVIRONMENT }} >> gatsby.development.env
          echo GATSBY_CONTENTFUL_HOST =${{ secrets.GATSBY_CONTENTFUL_HOST }} >> gatsby.development.env
          echo GATSBY_CONTENTFUL_SPACE_ID =${{ secrets.GATSBY_CONTENTFUL_SPACE_ID }} >> gatsby.development.env
          echo GATSBY_GTM_ID =${{ secrets.GATSBY_GTM_ID }} >> gatsby.development.env
          echo GATSBY_CONSENSYS_HOST =${{ secrets.GATSBY_CONSENSYS_HOST }} >> gatsby.development.env
          echo GATSBY_CONTENTFUL_PREVIEW_HOST =${{ secrets.GATSBY_CONTENTFUL_PREVIEW_HOST }} >> gatsby.development.env
          echo GATSBY_CONTENTFUL_PREVIEW_API_KEY =${{ secrets.GATSBY_CONTENTFUL_PREVIEW_API_KEY }} >> gatsby.development.env
          echo GH_TOKEN =${{ secrets.GH_TOKEN }} >> gatsby.development.env

      - name: Setup Node.js 🔧
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NVMRC }}

      - name: Cache Gatsby
        uses: actions/cache@v4
        id: cache-gatsby
        with:
          path: |
            .cache
            public
          key: ${{ runner.os }}-cache-gatsby-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-cache-gatsby

      
      - name: Cache Modules
        id: cache-modules
        uses: actions/cache@v4
        with:
          path: |
            node_modules
          key: ${{ runner.os }}-cache-modules-${{ hashFiles('**/yarn.lock')}}
          restore-keys: |
            ${{ runner.os }}-cache-modules-

      - name: Install Dependencies ⏳
        if: steps.cache-modules.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile

      - name: Build 🏗️
        run: yarn deploy:dev
        env:
          CI: true

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: public # The folder the action should deploy.
          clean: true # Automatically remove deleted files from the deploy branch
